---
- name: "Ensure the following directory exists: {{new_app_output_dir}}"
  file:
    path: "{{new_app_output_dir}}"
    state: directory
    mode: 0755

- name: Running Pre Workload Tasks
  import_tasks: ./pre_workload.yml
  become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision" or ACTION == "apimanager"

- name: Running Workload Tasks
  import_tasks: ./workload.yml
  become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision" or ACTION == "apimanager"

- name: Running Tenant Provision Tasks
  import_tasks: ./tenant_mgmt.yml
  become: "{{ become_override | bool }}"
  when: ACTION == ACTION == "create" or ACTION == "provision" or "tenant_mgmt"

- name: Running Post Workload Tasks
  import_tasks: ./post_workload.yml
  become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision" or ACTION == "apimanager"

- name: Running Workload removal Tasks
  import_tasks: ./remove_workload.yml
  become: "{{ become_override | bool }}"
  when: ACTION == "destroy" or ACTION == "remove"
